---

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'