---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # CentOS
  - name: CentOS-7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: "/usr/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro  # for ntp/timedatectl
    privileged: true
    pre_build_image: true
  - name: CentOS-8
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: "/usr/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro  # for ntp/timedatectl
    privileged: true
    pre_build_image: true

  # RHEL
  - name: RHEL-8
    image: "geerlingguy/docker-ubi8-ansible:latest"
    command: "/usr/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro  # for ntp/timedatectl
    privileged: true
    pre_build_image: true
  
  # Ubuntu
  - name: Ubuntu-16.04
    image: "geerlingguy/docker-ubuntu1604-ansible:latest"
    command: "/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro  # for ntp/timedatectl
    privileged: true
    pre_build_image: true
  - name: Ubuntu-18.04
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    command: "/lib/systemd/systemd"
    environment: { container: docker }
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro  # for ntp/timedatectl
    privileged: true
    pre_build_image: true
    
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
